FROM node:20

# Argument passed at build time that will be appended to .env.production (if the file doesn't exist it will just create it)
#ARG NEXT_PUBLIC_URL_API_URL=""
ARG DATABASE_URL
ARG RESEND_API_KEY
ARG SECRET_USER_KEY
ARG INIT_ADMIN_PASSWORD
ARG INIT_ADMIN_USERNAME
ARG INIT_ADMIN_EMAIL
ARG EMAIL_SYSTEM
ARG DEFAULT_KANBAN_INFO_PASSWORD
ARG DEFAULT_KANBAN_ADMIN_USERNAME
ARG DEFAULT_KANBAN_ADMIN_EMAIL
ARG DEFAULT_KANBAN_ADMIN_PASSWORD
ARG DEFAULT_VPS_EMAIL
ARG DEFAULT_PASS_VPS
ARG GITLAB_READ_TOKEN
ARG MONGO_USERNAME
ARG MONGO_PASSWORD
ARG EMAIL_NOTI
ARG MAIL_URL
ARG KANBAN_CLOUDFLARE_ZONE_ID
ARG API_CLOUDFLARE
ARG CLOUDFLARE_TOKEN
ARG VIETQR_API_URL
ARG VIETQR_BANK_ACCOUNT_NUMBER
ARG VIETQR_BANK_ACCOUNT_NAME
ARG VIETQR_BANK_ACQID
ARG VIETQR_CLIENT_ID
ARG VIETQR_API_KEY
ARG VIETQR_TEMPLATE
ARG DOMAIN
ARG NEXT_PUBLIC_CAPTCHA_SITE_KEY
ARG CAPTCHA_SECRET_KEY_NEW
ARG HOST_GITLAB
ARG GITLAB_PERSONAL_ACCESS_TOKEN
ARG PROJECT_ID
ARG REPOSITORY_ID
ARG EMAIL_BANK_ACCOUNT
ARG EMAIL_PASS_BANK_ACCOUNT
ARG OUTBOUND_TOKEN
ARG ENV
ARG EVENT_SERVICE_TOKEN
ARG EVENT_SERVICE_URL
ARG NEXT_PUBLIC_INTEGRATION_BOT_TELEGRAM

WORKDIR /usr/src/app

COPY package*.json ./
COPY nextjs-utils/ ./nextjs-utils/
RUN yarn install-all

COPY . .

# Build the site in production mode. .env.production is used
RUN echo "DATABASE_URL=$DATABASE_URL \n\
          RESEND_API_KEY=$RESEND_API_KEY \n\
          SECRET_USER_KEY=$SECRET_USER_KEY \n\
          INIT_ADMIN_PASSWORD=$INIT_ADMIN_PASSWORD \n\
          INIT_ADMIN_USERNAME=$INIT_ADMIN_USERNAME \n\
          INIT_ADMIN_EMAIL=$INIT_ADMIN_EMAIL \n\
          EMAIL_SYSTEM=$EMAIL_SYSTEM \n\
          DEFAULT_KANBAN_INFO_PASSWORD=$DEFAULT_KANBAN_INFO_PASSWORD \n\
          DEFAULT_KANBAN_ADMIN_USERNAME=$DEFAULT_KANBAN_ADMIN_USERNAME \n\
          DEFAULT_KANBAN_ADMIN_EMAIL=$DEFAULT_KANBAN_ADMIN_EMAIL \n\
          DEFAULT_KANBAN_ADMIN_PASSWORD=$DEFAULT_KANBAN_ADMIN_PASSWORD \n\
          DEFAULT_VPS_EMAIL=$DEFAULT_VPS_EMAIL \n\
          DEFAULT_PASS_VPS=$DEFAULT_PASS_VPS \n\
          GITLAB_READ_TOKEN=$GITLAB_READ_TOKEN \n\
          MONGO_USERNAME=$MONGO_USERNAME \n\
          MONGO_PASSWORD=$MONGO_PASSWORD \n\
          MAIL_URL=$MAIL_URL \n\
          EMAIL_NOTI=$EMAIL_NOTI \n\
          KANBAN_CLOUDFLARE_ZONE_ID=$KANBAN_CLOUDFLARE_ZONE_ID \n\
          API_CLOUDFLARE=$API_CLOUDFLARE \n\
          CLOUDFLARE_TOKEN=$CLOUDFLARE_TOKEN \n\
          VIETQR_API_URL=$VIETQR_API_URL \n\
          VIETQR_BANK_ACCOUNT_NUMBER=$VIETQR_BANK_ACCOUNT_NUMBER \n\
          VIETQR_BANK_ACCOUNT_NAME=$VIETQR_BANK_ACCOUNT_NAME \n\
          VIETQR_BANK_ACQID=$VIETQR_BANK_ACQID \n\
          VIETQR_CLIENT_ID=$VIETQR_CLIENT_ID \n\
          VIETQR_API_KEY=$VIETQR_API_KEY \n\
          VIETQR_TEMPLATE=$VIETQR_TEMPLATE \n\
          DOMAIN=$DOMAIN \n\
          NEXT_PUBLIC_CAPTCHA_SITE_KEY=$NEXT_PUBLIC_CAPTCHA_SITE_KEY \n\
          CAPTCHA_SECRET_KEY_NEW=$CAPTCHA_SECRET_KEY_NEW \n\
          HOST_GITLAB=$HOST_GITLAB \n\
          GITLAB_PERSONAL_ACCESS_TOKEN=$GITLAB_PERSONAL_ACCESS_TOKEN \n\
          PROJECT_ID=$PROJECT_ID \n\
          REPOSITORY_ID=$REPOSITORY_ID \n\
          EMAIL_BANK_ACCOUNT=$EMAIL_BANK_ACCOUNT \n\
          EMAIL_PASS_BANK_ACCOUNT=$EMAIL_PASS_BANK_ACCOUNT \n\
          OUTBOUND_TOKEN=$OUTBOUND_TOKEN \n\
          ENV=$ENV \n\
          EVENT_SERVICE_TOKEN=$EVENT_SERVICE_TOKEN \n\
          EVENT_SERVICE_URL=$EVENT_SERVICE_URL \n\
          NEXT_PUBLIC_INTEGRATION_BOT_TELEGRAM=$NEXT_PUBLIC_INTEGRATION_BOT_TELEGRAM \n" \
    >> .env

#build docker
RUN yarn prisma generate
RUN yarn build
RUN yarn install-mce

# I run my app on port 80 but you get the idea
EXPOSE 3000
RUN ["chmod" ,"+x" ,"./start-service.sh"]
ENTRYPOINT ["./start-service.sh"]