name: Check NextJs build

on:
  # Runs on any open or reopened pull request
  pull_request:
    branches:
      - develop

permissions:
  contents: read
  pages: write
  id-token: write


jobs:
  check-convention:
    runs-on: [ swifttech-package,self-hosted ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "20"
      - name: Check script
        run: yarn install-all && yarn check-format && yarn check-lint && yarn check-types && yarn build
      - name: Check build nextjs-utils
        run: cd nextjs-utils && yarn build && cd ..